[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mirisim_coronagraphy"
authors = [{name = "Becca", email = "bmichelson@smith.edu"}]
dynamic = ["version", "description"]
